language: ruby
bundler_args: --without guard
rvm:
  - "2.3.3"
  - "2.4.1"
  - ruby-head

script: "bundle exec rspec"
after_script: codeclimate-test-reporter

addons:
  code_climate:
    repo_token: '9b1e2d38c6d07358eab4a8a1ad4846df8d7f34bfdb9dc3f885dfc4ca44c16e4c'
branches:
  only: master
notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - env: RAILS_VERSION=master

env:
  matrix:
    # - "RAILS_VERSION=4.2"
    - "RAILS_VERSION=5.1"
    - "RAILS_VERSION=master"
